language: php
sudo: false
dist: trusty
php:
  - 7.2
  - 7.3
  - 7.4
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - composer self-update
  - composer update $DEPENDENCIES
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover;
  - if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then ./vendor/bin/php-cs-fixer --dry-run -v fix; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
